import XCTest
@testable import AgentProtocol

/// Every message Python can send, decoded by Swift.
///
/// `scripts/check_protocol.py` proves a field name exists on both sides. It cannot prove the
/// two sides agree on what the bytes mean — that a `null` is tolerated, that an enum spells
/// its cases the same way, that an optional is actually optional. This corpus can. It is
/// generated by `agentd.conformance`, which is the same code path the live server encodes
/// with, so an entry here is a message the server really emits.
///
/// Regenerate with `make protocol`.
final class ConformanceTests: XCTestCase {
    private struct Corpus: Decodable {
        let clientMessages: [JSONValue]
        let serverEvents: [JSONValue]
    }

    /// …/packages/Tests/AgentProtocolTests/ConformanceTests.swift -> …/packages
    private static let corpusURL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()      // AgentProtocolTests
        .deletingLastPathComponent()      // Tests
        .deletingLastPathComponent()      // packages
        .appendingPathComponent("AgentProtocol/conformance/corpus.json")

    private func corpus() throws -> Corpus {
        let data = try Data(contentsOf: Self.corpusURL)
        return try WireCodec.decoder.decode(Corpus.self, from: data)
    }

    private func encoded(_ value: JSONValue) throws -> Data {
        try WireCodec.encoder.encode(value)
    }

    private func type(of value: JSONValue) -> String {
        if case let .object(fields) = value, case let .string(name)? = fields["type"] {
            return name
        }
        return "<untyped>"
    }

    /// Every server event in the corpus decodes into a concrete case, not a dropped unknown.
    func testEveryServerEventDecodes() throws {
        let events = try corpus().serverEvents
        XCTAssertFalse(events.isEmpty)

        for entry in events {
            let name = type(of: entry)
            let event = try WireCodec.decoder.decode(ServerEvent.self, from: encoded(entry))
            XCTAssertNotNil(event, "\(name) did not decode")
        }
    }

    /// And survives a round trip, so the client can replay what it was sent.
    func testServerEventsRoundTripWithoutLoss() throws {
        for entry in try corpus().serverEvents {
            let name = type(of: entry)
            let event = try WireCodec.decoder.decode(ServerEvent.self, from: encoded(entry))
            let reencoded = try WireCodec.encoder.encode(event)
            let again = try WireCodec.decoder.decode(ServerEvent.self, from: reencoded)
            XCTAssertEqual(event, again, "\(name) changed meaning on re-encode")
        }
    }

    /// Every client message Python expects, Swift can produce and read back.
    func testEveryClientMessageDecodes() throws {
        let messages = try corpus().clientMessages
        XCTAssertFalse(messages.isEmpty)

        for entry in messages {
            let name = type(of: entry)
            let message = try WireCodec.decoder.decode(ClientMessage.self, from: encoded(entry))
            let reencoded = try WireCodec.encoder.encode(message)
            let again = try WireCodec.decoder.decode(ClientMessage.self, from: reencoded)
            XCTAssertEqual(message, again, "\(name) changed meaning on re-encode")
        }
    }

    /// The corpus has to cover the whole protocol, or it proves nothing about the gaps.
    func testCorpusCoversEveryMessageType() throws {
        let corpus = try corpus()
        let clientTypes = Set(corpus.clientMessages.map(type(of:)))
        let serverTypes = Set(corpus.serverEvents.map(type(of:)))

        XCTAssertEqual(clientTypes, [
            "hello", "userUtterance", "sceneUpdate", "deviceStates",
            "toolResult", "confirmationResult", "ping",
        ])
        XCTAssertEqual(serverTypes, [
            "ready", "token", "utteranceEnd", "characterDirective", "toolCall",
            "homeDevices", "ambientEvent", "requestPlace", "error", "pong",
        ])
    }

    /// Pydantic serialises absent optionals as `null` rather than omitting them, and the
    /// client has to treat that as absence — this is the shape live traffic actually has.
    func testExplicitNullsAreTreatedAsAbsent() throws {
        let event = try WireCodec.decodeEvent(
            #"{"type":"toolCall","callId":"c1","name":"list_devices","args":{},"safety":"safe","executedBy":"client"}"#
        )
        guard case let .toolCall(_, _, _, _, executedBy) = event else {
            return XCTFail("expected toolCall")
        }
        XCTAssertEqual(executedBy, .client)

        let directive = try WireCodec.decodeEvent(
            #"{"type":"characterDirective","directive":{"kind":"idle","place":null,"target":null,"deviceId":null,"emotion":null}}"#
        )
        XCTAssertEqual(directive, .characterDirective(CharacterDirective(kind: .idle)))
    }

    /// Every directive kind the character machine must handle appears in the corpus, since
    /// an unhandled kind is a character that freezes rather than an error anyone sees.
    func testCorpusCoversEveryDirectiveKind() throws {
        var kinds: Set<DirectiveKind> = []
        for entry in try corpus().serverEvents {
            let event = try WireCodec.decoder.decode(ServerEvent.self, from: encoded(entry))
            if case let .characterDirective(directive) = event { kinds.insert(directive.kind) }
        }
        XCTAssertEqual(kinds, [.walkTo, .lookAt, .point, .emote, .gesture, .idle])
    }
}
